from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
import io

def generate_docx(topic: str, sections: list) -> bytes:
    """Generate a beautifully formatted Word document"""
    
    doc = Document()
    
    # Set default font
    style = doc.styles['Normal']
    font = style.font
    font.name = 'Calibri'
    font.size = Pt(11)
    
    # Add Title
    title = doc.add_heading(topic, 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_run = title.runs[0]
    title_run.font.color.rgb = RGBColor(102, 126, 234)
    title_run.font.size = Pt(28)
    title_run.font.bold = True
    
    # Add spacing after title
    doc.add_paragraph()
    
    # Add sections
    for i, section in enumerate(sections, 1):
        # Section heading
        heading = doc.add_heading(f"{i}. {section['title']}", level=1)
        heading_run = heading.runs[0]
        heading_run.font.color.rgb = RGBColor(51, 51, 51)
        heading_run.font.size = Pt(18)
        
        # Section content
        content = section.get('content', '')
        if content:
            # Split into paragraphs
            paragraphs = content.split('\n\n')
            for para_text in paragraphs:
                if para_text.strip():
                    p = doc.add_paragraph(para_text.strip())
                    p.paragraph_format.line_spacing = 1.5
                    p.paragraph_format.space_after = Pt(12)
        
        # Add spacing after section
        doc.add_paragraph()
    
    # Add footer
    section = doc.sections[0]
    footer = section.footer
    footer_para = footer.paragraphs[0]
    footer_para.text = f"Generated by AI Document Generator"
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_para.runs[0].font.size = Pt(9)
    footer_para.runs[0].font.color.rgb = RGBColor(153, 153, 153)
    
    # Save to bytes
    file_stream = io.BytesIO()
    doc.save(file_stream)
    file_stream.seek(0)
    
    return file_stream.getvalue()